# Project info
site_name: IBM Engineering Lifecycle Management Level 3 Demonstration Guide
site_description: IBM Engineering Lifecycle Management Sales Enablement Level 3 Demonstration Guide
site_author: Andrew R. Jones (andrewj@us.ibm.com)
copyright: Copyright &copy; 2022 IBM

# Repository
repo_name: IBM/SalesEnablement-ELMhealthcare-L3
#repo_url: https://github.com/IBM/SalesEnablement-ELMhealthcare-L3
#edit_uri: edit/master/docs
docs_dir: docs


nav:
  - Introduction: 'index.md'
  - Overview:
    - 'The Demonstration': 'Part 1/01 Introduction.md'
    - 'Prerequisites': 'Prerequisites.md'
    - 'Demonstration Environment Preparation': 'Part 1/02 DemoPreparation.md'
  - Act 1:
    - 'Design Planning': 'Part 2/01 DesignPlanning.md'
  - Act 2:
    - 'Product Requirements': 'Part 3/01 ProductRequirements.md'
    - 'Change Management': 'Part 3/02 ConfigAndChangeMgmt.md'
  - Act 3:
    - 'Requirements Quality Assistant': 'Part 4/01 RQA.md'
    - 'Reviews': 'Part 4/02 Reviews.md'
    - 'Risk Management': 'Part 4/03 RiskManagement.md'
  - Act 4:
    - 'Design Verification': 'Part 5/01 DesignVerification.md'
    - 'Design Validation': 'Part 5/02 DesignValidation.md'
  - Act 5:
    - 'Engineering Insights for Metrics': 'Part 6/01 EngineeringInsights.md'
  - 'Next Steps': 'NextSteps.md'

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
    - mkdocs-video
    - macros
    - search

markdown_extensions:
  - sane_lists
  - pymdownx.details
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list

extra:
  generator: false
  learningplan:
    name: "IBM Engineering Lifecycle Management Level 3"
    url: "https://yourlearning.ibm.com/activity/PLAN-TBD"
  offering:
    name: "IBM Engineering Lifecycle Management"
  guide:
    name: "IBM Engineering Lifecycle Management - Level 3 Demonstration Guide"
    url: "https://ibm.github.io/SalesEnablement-ELMhealthcare-L3/"
  tz_environment:
    name: "ELM for Medical Demo Crate"
    environmentURL: "https://techzone.ibm.com/collection/elm-for-medical-demo-crate-hqe18dt4c"
    reservationURL: "https://techzone.ibm.com/my/reservations"
    windowsServerAdmin: "Administrator"
    windowsServerAdminPW: ""
    elmUserID: "Susan"
    adminPW: "il0vedem0s"
